# spring configuration
spring:
   application:
      name: service-emaillist
   profiles:
      active: development

            
---
# configuration: common
spring:
   cloud:
      config:
         enabled: true
         uri: http://localhost:7777


---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777
    
---

# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.181:7777
---

                              